<?php
///**
// * Created by PhpStorm.
// * User: maryam
// * Date: 9/15/2018
// * Time: 7:38 PM
// */
//
//namespace frontend\controllers;
//
//use common\components\jdf;
//use frontend\models\Backgrond;
//use frontend\models\Category;
//use frontend\models\Country;
//use frontend\models\Exhibitionn;
//use frontend\models\Img;
//use frontend\models\Participant;
//use frontend\models\Product;
//use frontend\models\Productmove;
//use frontend\models\Profile;
//use frontend\models\Views;
//use yii;
//use common\models\User;
//use yii\rest\ActiveController;
//use frontend\models\PHPWebSocket;
//
//class AndroidController extends ActiveController
//{
//
//    public $modelClass = 'frontend\models\Tblsize';
//
//
//    public function init()
//    {
//        if (\Yii::$app->request->authUser != null && \Yii::$app->request->authPassword != null) {
//
//            $username = \Yii::$app->request->authUser;;
//            $password = \Yii::$app->request->authPassword;
//            $user = User::findByUsername($username);
//            if ($user != null) {
//                if ($user->validatePassword($password)) {
//                    Yii::$app->getUser()->login($user);
//
//                } else {
//                    print "یوزر و پسورد شما اشتباه است";
//                    exit;
//                }
//            } else {
//                print "یوزر و پسورد را وارد کنید";
//                exit;
//            }
//        }
//
//        parent::init();
//        \Yii::$app->user->enableSession = false;
//    }
//
//
//    public function behaviors()
//    {
//        $behaviors = parent::behaviors();
//        $behaviors['authenticator'] = [
//            'class' => yii\filters\auth\HttpBasicAuth::className(),
//            'auth' => function ($user, $pass) {
//                $user = User::findByUsername($user);
//                if ($user != null) {
//                    return $user;
//                }
//
//            },
//            'only' => ['myorderse'],
//        ];
//        $behaviors['access'] = [
//
//            'class' => yii\filters\AccessControl::className(),
//            'only' => [],
//            'rules' => [
//                [
//                    'actions' => [],
//                    'allow' => true,
//                    'roles' => ['?'],
//                ],
//
//                [
//                    'actions' => [],
//                    'allow' => true,
//                    'roles' => ['@'],
//                ],
//            ],
//        ];
//
//        return $behaviors;
//    }
//
//    public function checkAccess($action, $model = null, $params = [])
//    {
//        return $model;
//    }
//
//    public function actions()
//    {
//        $action = parent::actions(); // TODO: Change the autogenerated stub
//        unset($action['create']);
//        return $action;
//    }
//
////my code
//
////send background app
//public function actionBackground(){
//    //این کد توی سرور کار نکرد
////    $back=Backgrond::find()->all();
////    foreach ($back as $b){
////        $backG=$b->backgrondImg;
////        $img=Img::find()->where(['id'=>$backG])->one();
////
////    }//end foreach
////   if ($img != null){
////       if ($img->fileImg != 'void'){
////           $send['fileImg']=Yii::$app->request->hostInfo ."/upload/images/". $img->fileImg;
////       }//end if fileImg != 'void'
////       else{
////           $send['fileImg']='void';
////       }
////
////   }//end img != null
////    else{}//end else img == null
////    $sendFull[]=$send;
////
////    $sendOk['fileImg'] = $sendFull;
////    $sendOk['result'] = 1;
////    return $sendOk;
//
//    //این کد روی سرور کار میکنه
//    $send['fileImg']=Yii::$app->request->hostInfo ."/upload/images/". 'background.jpg';
//    $send['result'] = 1;
//    return $send;
//
//}
//
////send country name for android
//    public function actionCountry()
//    {
//        $country = \frontend\models\Country::find()->all();
//
//        foreach ($country as $count) {
//            $idImg=$count->id_img;
//            $img=Img::find()->where(['enable'=>1])->andWhere(['id'=>$idImg])->one();
//            if ($img != null){
//                if ($img->fileImg != 'void'){
//                    $send['fileImg'] = Yii::$app->request->hostInfo . "/upload/images/" . $img->fileImg;
//                }//end if fileImg != 'void'
//            }//end if $img != null
//            $send['country'] = $count->country_name;
////            $send['fileImg']=$sendImg;
//            $send['id'] = $count->id;
//            $sendFull[] = $send;
//        }
//        $sendOk['country'] = $sendFull;
//        $sendOk['result'] = 1;
//        return $sendOk;
//    }
//
//    //receive country name in android and send exhibition name or msg for android
//    public function actionExhibition()
//    {
//        if (isset($_POST['id_country']) && $_POST['id_country'] != null) {
////            echo 2;exit;
////            $country=\frontend\models\Country::find()->all();
//            $exhibition = \frontend\models\Exhibitionn::find()->where(['id_country' => $_POST['id_country']])->andWhere(['enable'=>1])->all();
//            foreach ($exhibition as $exhibit) {
//                if ($exhibit != null) {
//                    //send image
//                    $id_img=$exhibit->image;
//                    $img=Img::find()->where(['enable'=>1])->andWhere(['id'=>$id_img])->one();
//                    if ($img != null){
//                        if ($img->fileImg != 'void'){
//                            $send['image']=Yii::$app->request->hostInfo.'/upload/images/'.$img->fileImg;
//                        }//enf if fileImg != 'void'
//                        else{
//                            $send['image']='void';
//                        }
//
//                    }//end if img != null
//                    else{
//                        $send['image']='void';
//                    }//end else img == null
//
//                    //send time (second)
//                    $start=$exhibit->holding_date_ir;
//                    $end=$exhibit->completion_date_ir;
//                    $start1=strtotime($start);
//                    $end1=strtotime($end);
//                    $time=$end1 - $start1;
//                    $send['time']=$time;
//
//
//                    $send['exhibition'] = $exhibit->title;
//                    $send['id'] = $exhibit->id;
//                    $send['id_country'] = $exhibit->id_country;
////                    $send['image'] = $exhibit->image;
//                    $send['holding_date'] = $exhibit->holding_date;
//                    $send['completion_date'] = $exhibit->completion_date;
//                    $send['holding_time'] = $exhibit->holding_time;
//                    $send['completion_time'] = $exhibit->completion_time;
//                    $sendFull[] = $send;
//                } else {
//                    $send['msg'] = 'لطفا در ایتدا نام کشور را انتخاب کنید.';
//                }
//            }
//
//            $sendOk['exhibition'] = $sendFull;
//            $sendOk['result'] = 1;
//            return $sendOk;
//        } else {
//            $send['result'] = 0;
//            $send['msg'] = 'لطفا در ایتدا نام کشور را انتخاب کنید.';
//            return $send;
//        }
//    }
//
//    //signup
//    public function actionSignup()
//    {
//
//        if (isset($_POST['role']) && $_POST['role'] != null
//            && isset($_POST['username']) && $_POST['username'] != null
//            && isset($_POST['password']) && $_POST['password'] != null
//            && isset($_POST['name']) && $_POST['name'] != null
//            && isset($_POST['company_name_ir']) && $_POST['company_name_ir'] != null
//            && isset($_POST['company_name_en']) && $_POST['company_name_en'] != null
//            && isset($_POST['telephone']) && $_POST['telephone'] != null
//            && isset($_POST['mobile']) && $_POST['mobile'] != null
//            && isset($_POST['rules']) && $_POST['rules'] != null
//        ) {
//
//            //  role      0=user  1=booth
//            if ($_POST['role'] == 0) {
//                $u = 'user';
//            } else {
//                $u = 'booth';
//            }
//
//
////باید نام شرکت یکتا باشد
//            $checkPro = Profile::find()->where(['company_name_ir' => $_POST['company_name_ir']])->andWhere(['company_name_en' => $_POST['company_name_en']])->count();
//
//            //if company_name was not
//            if ($checkPro == 0) {
//
//                $user = User::findByUsername($_POST['username']);
//                if ($user != null) {
//                    $send['result'] = 0;
//                    $send['msg'] = 'نام کاربری تکراری میباشد';
//                    return $send;
//                }
//
//                $user = new User();
//
//                $user->username = $_POST['username'];
//                $user->setPassword($_POST['password']);
//                $user->generateAuthKey();
//                $auth = Yii::$app->authManager;
////                    $authorRol=$auth->getRole($u);
//                if ($authorRol = $auth->getRole($u)) {
////                        var_dump($authorRol);exit;
////                        echo $authorRol;exit;
//                } else {
//                    echo 2;
//                    exit;
//                }
//
//
////                    if ($_POST['role'] == 0) {
////                        $authorRol1 = $auth->getRole('user');
////                    } else {
////                        $authorRol1 = $auth->getRole('booth');
////                    }
//                if ($user->save()) {
//
//                    $auth->assign($authorRol, $user->getId());
//                    $profile = new Profile();
//                    $profile->email = 'void';
//                    $profile->username = $_POST['username'];
//                    $profile->company_name_ir = $_POST['company_name_ir'];
//                    $profile->company_name_en = $_POST['company_name_en'];
//                    $profile->telephone = $_POST['telephone'];
//                    $profile->mobile = $_POST['mobile'];
//                    $profile->rules = $_POST['rules'];
//                    $profile->name = $_POST['name'];
//
//                    $profile->state = 0;
//                    $profile->id_img = -1;
//                    $profile->code = '00000000';
//                    $profile->first = 0;
//                    $profile->enable = 1;
//                    $profile->id_user = $user->getId();
//
//                    $data = new jdf();
//                    $profile->date = date('Y/m/d');
//                    $profile->date_ir = $data->date('Y/m/d');
//                    $profile->date_update = '2018/01/01';
//                    $profile->date_update_ir = '1397/05/01';
//
//                    $profile->role = $u;
////                        echo $profile->role;exit;
//
//                    if ($profile->save()) {
//                        $sendOk['result'] = 1;
//                        $sendOk['msg'] = 'ثبت نام با موفقیت انجام شد';
//                        return $sendOk;
//                    }//end if $profile save
//                    else {
////                        var_dump($profile->getErrors());exit;
//                        $send['result'] = 0;
//                        $send['msg'] = 'خطا در ثبت نام';
//                        return $send;
//                    }
//
//                }
//
//                //if company_name is was
//            } else {
//
//                $user = User::findByUsername($_POST['username']);
//                if ($user != null) {
//                    $send['result'] = 0;
//                    $send['msg'] = 'نام کاربری تکراری میباشد';
//                    return $send;
//                }
//
//                $co = 'void';
//                $com1 = $_POST['company_name_en'];
//                $com2 = $_POST['company_name_ir'];
//                $com = $com1 && $com2;
//
//                //save if company_name='void'
//                if ($com == $co) {
//                    $user = new User();
//
//                    $user->username = $_POST['username'];
//                    $user->setPassword($_POST['password']);
//                    $user->generateAuthKey();
//                    $auth = Yii::$app->authManager;
//                    $authorRol = $auth->getRole($u);
//
//                    if ($user->save()) {
//
//                        $auth->assign($authorRol, $user->getId());
//                        $profile = new Profile();
//                        $profile->email = 'void';
//                        $profile->username = $_POST['username'];
//                        $profile->company_name_ir = $_POST['company_name_ir'];
//                        $profile->company_name_en = $_POST['company_name_en'];
//                        $profile->telephone = $_POST['telephone'];
//                        $profile->mobile = $_POST['mobile'];
//                        $profile->rules = $_POST['rules'];
//                        $profile->name = $_POST['name'];
//
//                        $profile->state = 0;
//                        $profile->id_img = -1;
//                        $profile->code = '00000000';
//                        $profile->first = 0;
//                        $profile->enable = 1;
//                        $profile->id_user = $user->getId();
//
//                        $data = new jdf();
//                        $profile->date = date('Y/m/d');
//                        $profile->date_ir = $data->date('Y/m/d');
//                        $profile->date_update = '2018/01/01';
//                        $profile->date_update_ir = '1397/05/01';
//
//                        //$u=user or u=booth
//                        $profile->role = $u;
//
//
//                        if ($profile->save()) {
//                            $sendOk['result'] = 1;
//                            $sendOk['msg'] = 'ثبت نام با موفقیت انجام شد';
//                            $sendOk['id'] = $profile->id;
//                            $sendOk['id_user'] = $profile->id_img;
//                            return $sendOk;
//                        }//end if $profile save
//                        else {
////                            var_dump($profile->getErrors());exit;
//                            $send['result'] = 0;
//                            $send['msg'] = 'خطا در ثبت نام';
//                            return $send;
//                        }
//
//                    }
//
//
//                }//end if company_name !=void
//                else {
//                    $send['result'] = 0;
//                    $send['msg'] = 'نام شرکت تکراری میباشد';
//                    return $send;
//                }
//
//            }
//
//        } else {
//            $send['result'] = 0;
//            $send['msg'] = 'لطفا تمام اطلاعات را پر کنید';
////            $send['msg'] = 'لطفا داده ها را کامل وارد کنید';
//            return $send;
//        }
//    }
//
//    //login
//    public function actionLogin()
//    {
//        $request = Yii::$app->getRequest()->getBodyParam();
//        if (isset($_POST['username']) && $_POST['username'] != null
//            && isset($_POST['password']) && $_POST['password'] != null
//        ) {
//            $username = $request['username'];
//            $password = $request['password'];
//
//            $user = User::findByUsername($username);
//            if ($user != null) {
//
//                //for when I want to send data from the Profile table for Android
//                $profile = Profile::find()->where(['id_user' => $user->id])->one();
//
//                if ($user->validatePassword($password)) {
//                    Yii::$app->getUser()->login($user);
//
//                    //send id from user table
//                    $sendOk['id_user'] = $user->id;
//                    $sendOk['result'] = 1;
//                    return $sendOk;
//                }//end if validate
//                else {
//
//                    $send['result'] = 0;
//                    $send['msg'] = 'یوزر و پسورد اشتباه است';
//                    return $send;
//                }//end else validate
//
//            }//end if null
//            else {
//
//                $send['result'] = 0;
//                $send['msg'] = 'هیچ کاربری با این مشخصات یافت نشد.';
//                return $send;
//            }//end else null
//        }//end if isset
//        else {
//
//            $send['result'] = 0;
//            $send['msg'] = 'داده های ارسالی اشتباه است';
//            return $send;
//        }//end else isset
//    }
//
//    //send booth(participant) information for Android
//    //ارسال تمام غرفه داران یک نمایشگاه
//    public function actionParticipant()
//    {
//
//        //receive exhibition information
//        if (isset($_POST['id']) && $_POST['id'] != null
//            && isset($_POST['id_country']) && $_POST['id_country'] != null
//        ) {
//            $title = $_POST['id'];
//            $id_country = $_POST['id_country'];
//            $country = Country::find()->where(['id' => $id_country])->one();
//            if ($country) {
//
//                $exhibition = Exhibitionn::find()->where(['enable' => 1])->andWhere(['id_country' => $id_country])->andWhere(['id' => $title])->one();
//                if ($exhibition) {
//
//
//                    $participant = Participant::find()->where(['enable' => 1])->andWhere(['id_exhibitionn' => $exhibition->id])->all();
////            var_dump($participant);exit;
//
//                    if ($participant) {
//
//
//                        //send information
//                        foreach ($participant as $booth) {
//
//                            //send company name
//                            $id_company=$booth->id_company;
//                            $profile=Profile::find()->where(['enable'=>1])->andWhere(['id'=>$id_company])->one();
//                            if ($profile){
//                                $companyEn=$profile->company_name_en;
//                                $companyFa=$profile->company_name_ir;
//                                $send['companyEn']=$companyEn;
//                                $send['companyFa']=$companyFa;
//                            }//end if $profile != null
//
//
//                            $id_visits = $booth->id;
//
//                            //send images
//                            $id_img = $booth->id_images;
//                            if ($id_img != -1) {
//
////                    echo $id_img;exit;
//                                $images = Img::find()->where(['enable' => 1])->andWhere(['id' => $id_img])->andWhere(['id_participant' => $booth->id_company])->one();
//                                if ($images != null) {
//
//                                    $send1['fileImg'] = Yii::$app->request->hostInfo . "/upload/images/" . $images->fileImg;
//                                    $send1['fileMove'] = Yii::$app->request->hostInfo . "/upload/video/" . $images->fileMove;
//                                    $send1['filePdf'] = Yii::$app->request->hostInfo . "/upload/files/" . $images->filePdf;
//                                    $sendFullFile1[] = $send1;
//
//                                } else {
//
////                            $sendFullFile1[] = 'void';
//                                }
//
//
//                            } else {
//
////                        $sendFullFile1[] = 'void';
//                            }
//
//                            //send views
//                            $date = date('Y-m-d');
//                            $id = $id_visits;
//                            $view = Views::find()->where(['id_participant' => $id])->all();
//                            if ($view) {
//
//                                foreach ($view as $v) {
//                                    $viewDate = $v->date;
////                    var_dump($date);
////                    var_dump($viewDate);exit;
//                                    if ($viewDate == $date) {
//                                        $views = $v->visits;
//                                        $ok = 1;
//                                    }//end if $viewDate==$date
//                                    else {
//                                        $ok = 0;
//                                    }//end else $viewDate==$date
//
//                                }//end foreach
//
//
//                                if ($ok == 1) {
//                                    $visit = $views;
//                                } else {
//                                    $visit = 0;
//                                }
//                            }//end if view
//
////echo $visit;exit;
//                            $send['id'] = $booth->id;
//                            $send['id_room'] = $booth->id_room;
//                            $send['id_company'] = $booth->id_company;
//                            $send['id_activity'] = $booth->id_activity;
////                $send['teaser']=$booth->teaser;
//                            $send['responsible_name'] = $booth->responsible_name;
//                            $send['semat'] = $booth->semat;
//                            $send['email'] = $booth->email;
//                            $send['fax'] = $booth->fax;
//                            $send['site_address'] = $booth->site_address;
//                            $send['telegram'] = $booth->telegram;
//                            $send['instagram'] = $booth->instagram;
//                            $send['shortdescription'] = $booth->shortdescription;
//                            $send['description'] = $booth->dsescription;
//                            $send['images'] = $sendFullFile1;
//                            $send['visit'] = $visit;
//                            $sendFull[] = $send;
//                        }//end foreach
////                $sendOk['images']=$sendFullFile;
//                        $sendOk['visit'] = $visit;
//                        $sendOk['participant'] = $sendFull;
//                        $sendOk['result'] = 1;
//                        return $sendOk;
//
//                    }//if participant
//                    else {
//                        $send['result'] = 0;
//                        $send['msg'] = 'هیچ غرفه ای موجود نمیباشد';
//                        return $send;
//                    }
//                }//end if $exhibition
//                else {
//                    $send['result'] = 0;
//                    $send['msg'] = 'هیچ نمایشگاهی موجود نمیباشد';
//                    return $send;
//                }//end else exhibition
//
//            }//end if $country
//            else {
//                $send['result'] = 0;
//                $send['msg'] = 'چنین کشوری وجود ندارد';
//                return $send;
//            }//end else $country
//        }//end if isset
//        else {
//
//            $send['result'] = 0;
//            $send['msg'] = 'چنین اطلاعاتی وجود ندارد';
//            return $send;
//        }//end else isset
//    }
//
//    //send category
//    public
//    function actionCategory()
//    {
//    }
//
//    //send product
//    public function actionProduct(){
//
//        if (isset($_POST['id_participant']) && $_POST['id_participant'] != null) {
//
//            $id_participant = $_POST['id_participant'];
////                echo $id_participant;exit;
//
//            //send number of visits in app
//            $date = date('Y/m/d');
//            $view = Views::find()->where(['date' => $date])->andWhere(['id_participant' => $id_participant])->all();
//            $sumVisits = 0;
//            foreach ($view as $visit) {
//                $numberVisit = $visit->visits;
//                $sumVisits = $sumVisits + $numberVisit;
//            }
//
//            /*************************************************/
////save number of visits in app
//            $visitsPage = new Views();
//            $visitSum = 0;
//            $count = Views::find()->where(['id_participant' => $id_participant])->count();
//
//            if ($count == 0) {
//
//                $visitSum = $visitSum + 1;
//                $visitsPage->visits = $visitSum;
//                $visitsPage->id_participant = $id_participant;
//
//                $visitsPage->date = date('Y/m/d');
//                if ($visitsPage->save()) {
//
//                }//end if save
//                else {
//
//                    var_dump($visitsPage->getErrors());
//                    exit;
//                }//end else save
//
//            }//end if count
//            else {
//
//                $visit = Views::find()->where(['id_participant' => $id_participant])->all();
//                foreach ($visit as $view) {
//                    $newDate = date('Y/m/d');
//
//                    if ($view->date = $newDate) {
//
//                        $id = $view->id;
//                        $saveVisit = Views::find()->where(['id' => $id])->one();
//                        $visits = $saveVisit->visits;
//                        $visitSum = 1 + $visits;
//                        $saveVisit->visits = $visitSum;
//
//                        if ($saveVisit->save()) {
//
//                        }//end if save
//                        else {
//
//                            var_dump($visitsPage->getErrors());
//                            exit;
//                        }//end else save
//
//                    }//end if view->date
//                    else {
//
//                        $visitSum = $visitSum + 1;
//                        $visitsPage->visits = $visitSum;
//                        $visitsPage->id_participant = $id_participant;
//
//                        $visitsPage->date = date('Y/m/d');
//                        if ($visitsPage->save()) {
//
//                        }//end if save
//                        else {
//
//                            var_dump($visitsPage->getErrors());
//                            exit;
//                        }//end else save
//                    }//end else view->date
//                }
//
//            }//end else count
//
//            /********************************************/
//            //first category
//            $category = Category::find()->where(['enable' => 1])->andWhere(['id_participant' => $id_participant])->all();
//            if ($category) {
////var_dump($category);exit;
//                foreach ($category as $categor) {
//
//                    $id_category = $categor->id;
//                    $send['id'] = $categor->id;
//                    $send['title'] = $categor->title;
//                    $send['id_parent'] = $categor->id_parent;
//                    $send['id_img'] = $categor->id_img;
//                    $send['description'] = $categor->description;
//
//                    $sendCategoryOk[] = $send;
//                    //second product
//
//                    $product = Product::find()->where(['enable' => 1])->andWhere(['id_Category' => $id_category])->all();
////                    var_dump($product);exit;
////                    if ($product) {//با بین شرط محصولات نمایش داده نمیشن
//
//                        foreach ($product as $pro) {
//                            $id_img = $pro->id_img;
//                            if ($id_img != -1) {
//
//
//                                $movie = Productmove::find()->where(['enable' => 1])->andWhere(['id' => $id_img])->andWhere(['id_product' => $pro->id])->one();
//                                if ($movie != null) {
//
//
////                                    if ($movie->move1 !='void'){
////                                        $sendMovie['movie1'] = Yii::$app->request->hostInfo . '/upload/video/' . $movie->move1;
//////                                        $name=$movie->move1;
//////                                        $all=Yii::getAlias('@upload').'/upload/video/'.$name;
//////                                        $allExplode=explode('*',$all);
//////                                        $count=count($allExplode);
//////                                        for ($i=0 ;$i<$count ; $i++){
//////
//////                                            $sendMovie['movie1'] = Yii::$app->request->hostInfo . '/upload/video/' . $allExplode[$i];
//////                                        }//end for
//////                                        var_dump($i);exit;
////
////                                    }
//                                    if ($movie->move1 != 'void'){
//                                        $sendMovie['movie1'] = Yii::$app->request->hostInfo . "/upload/files/" . $movie->move1;
//                                    }
//                                    if ($movie->move2 !='void'){
//                                        $sendMovie['movie2'] = Yii::$app->request->hostInfo . "/upload/files/" . $movie->move2;
//                                    }
//                                    if ($movie->move3 !='void'){
//                                        $sendMovie['movie3'] = Yii::$app->request->hostInfo . "/upload/images/" . $movie->move3;
//                                    }
//
//                                    $sendFileMovie[] = $sendMovie;
//
////
//                                }//end if $movie
//                                else {
////                                    $sendFileMovie[] = 'void';
//                                }//end else $movie
//
//                            }//end if $id_img
//                            else {
////                                $sendFileMovie[] = 'void';
//                            }//end else $id_img
////                            var_dump($sendMovie);exit;
//                            $send['id'] = $pro->id;
//                            $send['title'] = $pro->title;
//                            $send['id_participant'] = $pro->id_participant;
//                            $send['typePro'] = $pro->typePro;
//                            $send['id_category'] = $pro->id_Category;
//                            $send['description'] = $pro->description;
//                            if ($sendFileMovie != 'void'){
//                                $send['id_img'] = $sendFileMovie;
//                            }//end if $sendFileMovie
//                            else {$send['id_img']='void';}
//
//                            $sendFull[] = $send;
//
//
//                        }//end foreach
//
////با بین شرط محصولات نمایش داده نمیشن
////                    }//end if product
////                    else {
////                        $send['visits of page'] = $sumVisits;
////                        $send['category'] = $sendCategoryOk;
////                        $send['result'] = 0;
////                        $send['msg'] = 'در این غرفه هیچ محصولی وجود ندارد';
////                        return $send;
////
////                    }
//
//                }//end foreach $category
//
//            }//ens if $category
//            else {
//                $send['visits of page'] = $sumVisits;
////                    $send['category'] = $sendCategoryOk;
//                $send['result'] = 0;
//                $send['msg'] = 'در این غرفه هیچ دسته بندی وجود ندارد';
//                return $send;
//
//            }//end else $category
//            $sendOk['visits of page'] = $sumVisits;
//            $sendOk['category'] = $sendCategoryOk;
//            $sendOk['product'] = $sendFull;
//            $sendOk['result'] = 1;
//            return $sendOk;
//
//        }//end isset
//        else {
//
//            $send['result'] = 0;
//            $send['msg'] = 'در حال حاضر چنین غرفه ای وجود ندارد';
//            return $send;
//        }//end else isset
//    }
//
//    //send number of visits in app
//    public function actionViews(){
////        $view=Views::find()->all();
//        $date = date('Y/m/d');
//        $view = Views::find()->where(['date' => $date])->all();
//        $sumVisits = 0;
//        foreach ($view as $visit) {
//            $numberVisit = $visit->visits;
//            $sumVisits = $sumVisits + $numberVisit;
//        }
//        echo $numberVisit;
//        exit;
//
//    }
//
//    //send view visitirs
//    public function actionViewapp(){
//        if (isset($_POST['id_participant']) && $_POST['id_participant'] != null) {
//            $date = date('Y-m-d');
//            $id = $_POST['id_participant'];
//            $view = Views::find()->where(['id_participant' => $id])->all();
//            if ($view) {
//
//                foreach ($view as $v) {
//                    $viewDate = $v->date;
////                    var_dump($date);
////                    var_dump($viewDate);exit;
//                    if ($viewDate == $date) {
//                        $views = $v->visits;
//                        $ok = 1;
//                    }//end if $viewDate==$date
//                    else {
//                        $ok = 0;
//                    }//end else $viewDate==$date
//
//                }//end foreach
//
//                if ($ok == 1) {
//                    $sendOk['result'] = 1;
//                    $sendOk['visits'] = $views;
//                    $sendOk['msg'] = 'تعداد بازدید های امروز این غرفه';
//                    return $sendOk;
//                }//end if ok
//                else {
//
//                    $send['result'] = 0;
//                    $send['msg'] = 'غرفهای وجود ندارد';
//                    return $send;
//                }//end else ok
//
//            }//end if $views
//            else {
//
//                $send['result'] = 0;
//                $send['msg'] = 'غرفهای وجود ندارد';
//                return $send;
//            }//end else $views
//        }//end if isset
//        else {
//            $send['result'] = 0;
//            $send['msg'] = 'لطفا در ایتدا نام غرفه را انتخاب کنید.';
//            return $send;
//        }
//
//    }
//
//}

///********************************************************************************************************************/


/**
 * Created by PhpStorm.
 * User: maryam
 * Date: 9/15/2018
 * Time: 7:38 PM
 */

namespace frontend\controllers;

use common\components\jdf;
use frontend\models\Backgrond;
use frontend\models\Category;
use frontend\models\Country;
use frontend\models\Exhibitionn;
use frontend\models\Factor;
use frontend\models\Img;
use frontend\models\Nextexhibition;
use frontend\models\Participant;
use frontend\models\Product;
use frontend\models\Productmove;
use frontend\models\Profile;
use frontend\models\Views;
use yii;
use common\models\User;
use yii\rest\ActiveController;
use frontend\models\PHPWebSocket;

class AndroidController extends ActiveController
{

    public $modelClass = 'frontend\models\Tblsize';


    public function init()
    {
        if (\Yii::$app->request->authUser != null && \Yii::$app->request->authPassword != null) {

            $username = \Yii::$app->request->authUser;;
            $password = \Yii::$app->request->authPassword;
            $user = User::findByUsername($username);
            if ($user != null) {
                if ($user->validatePassword($password)) {
                    Yii::$app->getUser()->login($user);

                } else {
                    print "یوزر و پسورد شما اشتباه است";
                    exit;
                }
            } else {
                print "یوزر و پسورد را وارد کنید";
                exit;
            }
        }

        parent::init();
        \Yii::$app->user->enableSession = false;
    }


    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => yii\filters\auth\HttpBasicAuth::className(),
            'auth' => function ($user, $pass) {
                $user = User::findByUsername($user);
                if ($user != null) {
                    return $user;
                }

            },
            'only' => ['myorderse'],
        ];
        $behaviors['access'] = [

            'class' => yii\filters\AccessControl::className(),
            'only' => [],
            'rules' => [
                [
                    'actions' => [],
                    'allow' => true,
                    'roles' => ['?'],
                ],

                [
                    'actions' => [],
                    'allow' => true,
                    'roles' => ['@'],
                ],
            ],
        ];

        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        return $model;
    }

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['create']);
        return $action;
    }

//my code

//send background app
    public function actionBackground()
    {
//     $back=Backgrond::find()->all();
//     foreach ($back as $b){
//         $backG=$b->backgrondImg;
//         $img=Img::find()->where(['id'=>$backG])->one();

//     }//end foreach
//   if ($img != null){
//       if ($img->fileImg != 'void'){
//           $send['fileImg']=Yii::$app->request->hostInfo ."/upload/images/". $img->fileImg;
//       }//end if fileImg != 'void'
//       else{
//           $send['fileImg']='void';
//       }

//   }//end img != null
//     else{}//end else img == null
//     $sendFull[]=$send;

//     $sendOk['fileImg'] = $sendFull;
//     $sendOk['result'] = 1;
//     return $sendOk;
        $next = Nextexhibition::find()->where(['enable' => 1])->one();


        $send['nextExhibition'] = $next->nextExhibition;
        $send['fileImg'] = Yii::$app->request->hostInfo . "/upload/images/" . 'background.jpg';
        $send['result'] = 1;
        return $send;


    }

//send country name for android
    public function actionCountry()
    {
        $country = \frontend\models\Country::find()->all();

        foreach ($country as $count) {

            // $idImg=$count->id_img;
            // $img=Img::find()->where(['enable'=>1])->andWhere(['id'=>$idImg])->one();
            // if ($img != null){
            //     if ($img->fileImg != 'void'){
            //         $send['fileImg'] = Yii::$app->request->hostInfo . "/upload/images/" . $img->fileImg;
            //     }//end if fileImg != 'void'
            // }//end if $img != null

            $send['country'] = $count->country_name;
//            $send['fileImg']=$sendImg;
            $send['id'] = $count->id;
            $sendFull[] = $send;
        }

        $sendOk['country'] = $sendFull;
        $sendOk['result'] = 1;
        return $sendOk;
    }

    //receive country name in android and send exhibition name or msg for android
    public function actionExhibition()
    {
        if (isset($_POST['id_country']) && $_POST['id_country'] != null) {
//            echo 2;exit;
//            $country=\frontend\models\Country::find()->all();
            $exhibition = \frontend\models\Exhibitionn::find()->where(['id_country' => $_POST['id_country']])->andWhere(['enable' => 1])->all();
            foreach ($exhibition as $exhibit) {
                if ($exhibit != null) {
                    //send image
                    $id_img = $exhibit->image;
                    $img = Img::find()->where(['enable' => 1])->andWhere(['id' => $id_img])->one();
                    if ($img != null) {
                        if ($img->fileImg != 'void') {
                            $send['image'] = Yii::$app->request->hostInfo . '/upload/images/' . $img->fileImg;
                        }//enf if fileImg != 'void'
                        else {
                            $send['image'] = 'void';
                        }

                    }//end if img != null
                    else {
                        $send['image'] = 'void';
                    }//end else img == null

                    //send time (second)
                    $start = $exhibit->holding_date_ir;
                    $end = $exhibit->completion_date_ir;
                    $start1 = strtotime($start);
                    $end1 = strtotime($end);
                    $time = $end1 - $start1;
                    $send['time'] = $time;


                    $send['exhibition'] = $exhibit->title;
                    $send['id'] = $exhibit->id;
                    $send['id_country'] = $exhibit->id_country;
//                    $send['image'] = $exhibit->image;
                    $send['holding_date'] = $exhibit->holding_date;
                    $send['completion_date'] = $exhibit->completion_date;
                    $send['holding_time'] = $exhibit->holding_time;
                    $send['completion_time'] = $exhibit->completion_time;
                    $sendFull[] = $send;
                } else {
                    $send['msg'] = 'لطفا در ایتدا نام کشور را انتخاب کنید.';
                }
            }

            $sendOk['exhibition'] = $sendFull;
            $sendOk['result'] = 1;
            return $sendOk;
        } else {
            $send['result'] = 0;
            $send['msg'] = 'لطفا در ایتدا نام کشور را انتخاب کنید.';
            return $send;
        }
    }

    //signup
    public function actionSignup()
    {

        if (isset($_POST['role']) && $_POST['role'] != null
            && isset($_POST['username']) && $_POST['username'] != null
            && isset($_POST['password']) && $_POST['password'] != null
            && isset($_POST['name']) && $_POST['name'] != null
            && isset($_POST['company_name_ir']) && $_POST['company_name_ir'] != null
            && isset($_POST['company_name_en']) && $_POST['company_name_en'] != null
            && isset($_POST['telephone']) && $_POST['telephone'] != null
            && isset($_POST['mobile']) && $_POST['mobile'] != null
            && isset($_POST['rules']) && $_POST['rules'] != null
        ) {

            //  role      0=user  1=booth
            if ($_POST['role'] == 0) {
                $u = 'user';
            } else {
                $u = 'booth';
            }


//باید نام شرکت یکتا باشد
            $checkPro = Profile::find()->where(['company_name_ir' => $_POST['company_name_ir']])->andWhere(['company_name_en' => $_POST['company_name_en']])->count();

            //if company_name was not
            if ($checkPro == 0) {

                $user = User::findByUsername($_POST['username']);
                if ($user != null) {
                    $send['result'] = 0;
                    $send['msg'] = 'نام کاربری تکراری میباشد';
                    return $send;
                }

                $user = new User();

                $user->username = $_POST['username'];
                $user->setPassword($_POST['password']);
                $user->generateAuthKey();
                $auth = Yii::$app->authManager;
//                    $authorRol=$auth->getRole($u);
                if ($authorRol = $auth->getRole($u)) {
//                        var_dump($authorRol);exit;
//                        echo $authorRol;exit;
                } else {
                    echo 2;
                    exit;
                }


//                    if ($_POST['role'] == 0) {
//                        $authorRol1 = $auth->getRole('user');
//                    } else {
//                        $authorRol1 = $auth->getRole('booth');
//                    }
                if ($user->save()) {

                    $auth->assign($authorRol, $user->getId());
                    $profile = new Profile();
                    $profile->email = 'void';
                    $profile->username = $_POST['username'];
                    $profile->company_name_ir = $_POST['company_name_ir'];
                    $profile->company_name_en = $_POST['company_name_en'];
                    $profile->telephone = $_POST['telephone'];
                    $profile->mobile = $_POST['mobile'];
                    $profile->rules = $_POST['rules'];
                    $profile->name = $_POST['name'];

                    $profile->state = 0;
                    $profile->id_img = -1;
                    $profile->code = '00000000';
                    $profile->first = 0;
                    $profile->enable = 1;
                    $profile->id_user = $user->getId();

                    $data = new jdf();
                    $profile->date = date('Y/m/d');
                    $profile->date_ir = $data->date('Y/m/d');
                    $profile->date_update = '2018/01/01';
                    $profile->date_update_ir = '1397/05/01';

                    $profile->role = $u;
//                        echo $profile->role;exit;

                    if ($profile->save()) {
                        $sendOk['result'] = 1;
                        $sendOk['msg'] = 'ثبت نام با موفقیت انجام شد';
                        return $sendOk;
                    }//end if $profile save
                    else {
//                        var_dump($profile->getErrors());exit;
                        $send['result'] = 0;
                        $send['msg'] = 'خطا در ثبت نام';
                        return $send;
                    }

                }

                //if company_name is was
            } else {

                $user = User::findByUsername($_POST['username']);
                if ($user != null) {
                    $send['result'] = 0;
                    $send['msg'] = 'نام کاربری تکراری میباشد';
                    return $send;
                }

                $co = 'void';
                $com1 = $_POST['company_name_en'];
                $com2 = $_POST['company_name_ir'];
                $com = $com1 && $com2;

                //save if company_name='void'
                if ($com == $co) {
                    $user = new User();

                    $user->username = $_POST['username'];
                    $user->setPassword($_POST['password']);
                    $user->generateAuthKey();
                    $auth = Yii::$app->authManager;
                    $authorRol = $auth->getRole($u);

                    if ($user->save()) {

                        $auth->assign($authorRol, $user->getId());
                        $profile = new Profile();
                        $profile->email = 'void';
                        $profile->username = $_POST['username'];
                        $profile->company_name_ir = $_POST['company_name_ir'];
                        $profile->company_name_en = $_POST['company_name_en'];
                        $profile->telephone = $_POST['telephone'];
                        $profile->mobile = $_POST['mobile'];
                        $profile->rules = $_POST['rules'];
                        $profile->name = $_POST['name'];

                        $profile->state = 0;
                        $profile->id_img = -1;
                        $profile->code = '00000000';
                        $profile->first = 0;
                        $profile->enable = 1;
                        $profile->id_user = $user->getId();

                        $data = new jdf();
                        $profile->date = date('Y/m/d');
                        $profile->date_ir = $data->date('Y/m/d');
                        $profile->date_update = '2018/01/01';
                        $profile->date_update_ir = '1397/05/01';

                        //$u=user or u=booth
                        $profile->role = $u;


                        if ($profile->save()) {
                            $sendOk['result'] = 1;
                            $sendOk['msg'] = 'ثبت نام با موفقیت انجام شد';
                            $sendOk['id'] = $profile->id;
                            $sendOk['id_user'] = $profile->id_img;
                            return $sendOk;
                        }//end if $profile save
                        else {
//                            var_dump($profile->getErrors());exit;
                            $send['result'] = 0;
                            $send['msg'] = 'خطا در ثبت نام';
                            return $send;
                        }

                    }


                }//end if company_name !=void
                else {
                    $send['result'] = 0;
                    $send['msg'] = 'نام شرکت تکراری میباشد';
                    return $send;
                }

            }

        } else {
            $send['result'] = 0;
            $send['msg'] = 'لطفا تمام اطلاعات را پر کنید';
//            $send['msg'] = 'لطفا داده ها را کامل وارد کنید';
            return $send;
        }
    }

    //login
    public function actionLogin()
    {
        $request = Yii::$app->getRequest()->getBodyParam();
        if (isset($_POST['username']) && $_POST['username'] != null
            && isset($_POST['password']) && $_POST['password'] != null
        ) {
            $username = $request['username'];
            $password = $request['password'];

            $user = User::findByUsername($username);
            if ($user != null) {

                //for when I want to send data from the Profile table for Android
                $profile = Profile::find()->where(['id_user' => $user->id])->one();

                if ($user->validatePassword($password)) {
                    Yii::$app->getUser()->login($user);

                    //send id from user table
                    $sendOk['id_user'] = $user->id;
                    $sendOk['result'] = 1;
                    return $sendOk;
                }//end if validate
                else {

                    $send['result'] = 0;
                    $send['msg'] = 'یوزر و پسورد اشتباه است';
                    return $send;
                }//end else validate

            }//end if null
            else {

                $send['result'] = 0;
                $send['msg'] = 'هیچ کاربری با این مشخصات یافت نشد.';
                return $send;
            }//end else null
        }//end if isset
        else {

            $send['result'] = 0;
            $send['msg'] = 'داده های ارسالی اشتباه است';
            return $send;
        }//end else isset
    }

    //send booth(participant) information for Android
    //ارسال تمام غرفه داران یک نمایشگاه
    public function actionParticipant()
    {

        //receive exhibition information
        if (isset($_POST['id']) && $_POST['id'] != null
            && isset($_POST['id_country']) && $_POST['id_country'] != null
        ) {

            $title = $_POST['id'];
            $id_country = $_POST['id_country'];
            $country = Country::find()->where(['id' => $id_country])->one();
            if ($country) {

                $exhibition = Exhibitionn::find()->where(['enable' => 1])->andWhere(['id_country' => $id_country])->andWhere(['id' => $title])->one();
                if ($exhibition) {

                    $dateExhibition = $exhibition->completion_date_ir;

                    $participant = Participant::find()->where(['enable' => 1])->andWhere(['id_exhibitionn' => $exhibition->id])->all();

                    if ($participant) {


                        //send advertises
//                        $advertiseFactor=Factor::find()->where(['enable'=>1])->andWhere(['id_advertise'=> 0])->andWhere(['buyAdvertise'=>1])->all();
                        $advertiseFactor = Factor::find()->where(['enable' => 1])->andWhere(['buyAdvertise' => 1])->all();
                        if ($advertiseFactor != null) {
                            foreach ($advertiseFactor as $advertise) {
                                $img = $advertise->id_advertise;
                                $movie = Productmove::find()->where(['enable' => 1])->andWhere(['id' => $img])->one();
                                $profile1 = Profile::find()->where(['enable' => 1])->andWhere(['id' => $advertise->id_company])->one();
                                if ($movie != null) {
                                    $sendPathA['title'] = $profile1->company_name_ir;
                                    $sendPathA['caption'] = $profile1->telephone;
                                    $sendPathA['url'] = Yii::$app->request->hostInfo . "/upload/image/" . $movie->move3;
                                    $sendPathA['move'] = Yii::$app->request->hostInfo . "/upload/video/" . $movie->move1;
//                                    $participant1=Participant::find()->where(['enable'=>1])->andWhere(['id'=>])->one();
                                    $sendPathA['id'] = $advertise->id_participant;
//                                    if ($advertise->id_participant != -1){
//                                        $sendPathA['id']=$advertise->id_participant;
//                                    }else{
//                                        $sendPathA['id']=$advertise->id_participant;
//                                    }


                                    $sendFullFileA[] = $sendPathA;


                                } else {
                                    $sendFullFileA[] = 'void';
                                }


                            }//end foreach Advertise
                        } else {
                            $sendFullFileA[] = 'void';
                        }

//                        $a['as']=$sendPathA;

                        //send information
                        foreach ($participant as $booth) {

                            //send company name
                            $id_company = $booth->id_company;
                            $profile = Profile::find()->where(['enable' => 1])->andWhere(['id' => $id_company])->one();
                            if ($profile) {
                                $companyEn = $profile->company_name_en;
                                $companyFa = $profile->company_name_ir;
                                $send['companyEn'] = $companyEn;
                                $send['companyFa'] = $companyFa;
                            }//end if $profile != null


                            $id_visits = $booth->id;

                            //send images
                            $id_img = $booth->id_images;
                            if ($id_img != -1) {

//                    echo $id_img;exit;
//
                                $images = Img::find()->where(['enable' => 1])->andWhere(['id' => $id_img])->andWhere(['id_participant' => $booth->id_company])->one();
                                if ($images != null) {
                                    unset($sendFullFile1);
                                    $send1['fileImg'] = Yii::$app->request->hostInfo . "/upload/images/" . $images->fileImg;
                                    $send1['fileMove'] = Yii::$app->request->hostInfo . "/upload/video/" . $images->fileMove;
                                    $send1['filePdf'] = Yii::$app->request->hostInfo . "/upload/files/" . $images->filePdf;
                                    $send1['id'] = $images->id;


                                } else {

//                            $sendFullFile1[] = 'void';
                                }
                                $sendFullFile1[] = $send1;

                            } else {

//                        $sendFullFile1[] = 'void';
                            }

                            //send views
//                            $date = date('Y-m-d');
                            $id = $id_visits;
                            $view = Views::find()->where(['id_participant' => $id])->all();
                            if ($view) {

                                foreach ($view as $v) {
                                    $viewDate = $v->date;
//                    var_dump($date);
//                    var_dump($viewDate);exit;
                                    if ($viewDate == $dateExhibition) {
                                        $views = $v->visits;
                                        $ok = 1;
                                    }//end if $viewDate==$date
                                    else {
                                        $ok = 0;
                                    }//end else $viewDate==$date

                                }//end foreach


                                if ($ok == 1) {
                                    $visit = $views;
                                } else {
                                    $visit = 0;
                                }
                            }//end if view
                            else {
                                $visit = 0;
                            }

//echo $visit;exit;
                            $send['id'] = $booth->id;
                            $send['id_room'] = $booth->id_room;
                            $send['id_company'] = $booth->id_company;
                            $send['id_activity'] = $booth->id_activity;
//                $send['teaser']=$booth->teaser;
                            $send['responsible_name'] = $booth->responsible_name;
                            $send['semat'] = $booth->semat;
                            $send['email'] = $booth->email;
                            $send['fax'] = $booth->fax;
                            $send['site_address'] = $booth->site_address;
                            $send['telegram'] = $booth->telegram;
                            $send['instagram'] = $booth->instagram;
                            $send['shortdescription'] = $booth->shortdescription;
                            $send['description'] = $booth->dsescription;
                            $send['images'] = $sendFullFile1;
                            $send['visit'] = $visit;
                            $sendFull[] = $send;
                        }//end foreach

//                $sendOk['images']=$sendFullFile;
//                        $sendOk['visit'] = $visit;
                        $sendOk['s'] = $sendFullFileA;
                        $sendOk['participant'] = $sendFull;
                        $sendOk['result'] = 1;
                        return $sendOk;

                    }//if participant
                    else {
                        $send['result'] = 0;
                        $send['msg'] = 'هیچ غرفه ای موجود نمیباشد';
                        return $send;
                    }
                }//end if $exhibition
                else {
                    $send['result'] = 0;
                    $send['msg'] = 'هیچ نمایشگاهی موجود نمیباشد';
                    return $send;
                }//end else exhibition

            }//end if $country
            else {
                $send['result'] = 0;
                $send['msg'] = 'چنین کشوری وجود ندارد';
                return $send;
            }//end else $country
        }//end if isset
        else {

            $send['result'] = 0;
            $send['msg'] = 'چنین اطلاعاتی وجود ندارد';
            return $send;
        }//end else isset
    }

    //send product
    public function actionProduct()
    {

        if (isset($_POST['id_participant']) && $_POST['id_participant'] != null) {

            $id_participant = $_POST['id_participant'];
            /*************************************************************************************************/
            //send number of visits in app
            $participant = Participant::find()->where(['id' => $id_participant])->andWhere(['enable' => 1])->one();
            $idExhibition = $participant->id_exhibitionn;
            $exhibition = Exhibitionn::find()->where(['enable' => 1])->andWhere(['id' => $idExhibition])->one();
            $exhibitionHistory = $exhibition->completion_date_ir;
            $date = date('Y/m/d');//today
            $view = Views::find()->where(['date' => $exhibitionHistory])->andWhere(['id_participant' => $id_participant])->andWhere(['enable' => 1])->all();
            $sumVisits = 0;
            if ($view) {
                foreach ($view as $visit) {
                    $numberVisit = $visit->visits;
                    $sumVisits = $sumVisits + $numberVisit;
                }
            }//end if $view
            else {

            }

            /*************************************************/
//save number of visits in app
            $visitsPage = new Views();
            $visitSum = 0;
            $count = Views::find()->where(['id_participant' => $id_participant])->andWhere(['date' => $exhibitionHistory])->andWhere(['enable' => 1])->count();

            if ($count == 0) {

                $todayDate = date('Y-m-d');//today date

                $visitSum = $visitSum + 1;
                $visitsPage->visits = $visitSum;
                $visitsPage->id_participant = $id_participant;
                $visitsPage->date = $exhibitionHistory;
                if ($todayDate <= $exhibitionHistory) {
                    if ($visitsPage->save()) {


                    }//end if save
                    else {

                        var_dump($visitsPage->getErrors());
                        exit;
                    }//end else save
                }//end if date is today smaller than date exhibition
                else {

                }//end if date is today larger than date exhibition

            }//end if count
            else {

                $visit = Views::find()->where(['id_participant' => $id_participant])->andWhere(['date' => $exhibitionHistory])->andWhere(['enable' => 1])->all();
                foreach ($visit as $view) {

                    $newDate = date('Y-m-d');
//                    echo $view->date;

                    if ($newDate <= $exhibitionHistory) {

                        $id = $view->id;
                        $saveVisit = Views::find()->where(['id_participant' => $id_participant])->andWhere(['date' => $exhibitionHistory])->andWhere(['enable' => 1])->all();
                        $x = 0;
//                        foreach ($saveVisit as $visitS){

                        $visits = $view->visits;
                        $visitSum = 1 + $visits;
                        $view->visits = $visitSum;
                        if ($view->save()) {

                        }//end if save
                        else {

                            var_dump($view->getErrors());
                            exit;
                        }//end else save


//                        }//end foreach saveVisit
//                        $visitS->visits = $visitSum;
//exit;
                    }//end if view->date
                    else {

//                        $visitSum = $visitSum + 1;
//                        $visitsPage->visits = $visitSum;
//                        $visitsPage->id_participant = $id_participant;
//
////                        $visitsPage->date = date('Y/m/d');
//                        $visitsPage->date = $exhibitionHistory;
//                        if ($visitsPage->save()) {
//
//                        }//end if save
//                        else {
//
//                            var_dump($visitsPage->getErrors());
//                            exit;
//                        }//end else save
                    }//end else view->date
//
                }

            }//end else count

            /********************************************/
            //first category

            $category = Category::find()->where(['enable' => 1])->andWhere(['id_participant' => $id_participant])->all();

            if ($category) {

                foreach ($category as $categor) {

                    //send imageCategory
                    $idImg = $categor->id_img;
                    if ($idImg != 0 && $idImg != -1) {

                        $categoryImg = Img::find()->where(['enable' => 1])->andWhere(['id' => $idImg])->one();

                        if ($categoryImg != null) {

                            $imgName = $categoryImg->fileImg;

                            if ($imgName != 'void') {
                                $sendPath['img'] = Yii::$app->request->hostInfo . '/upload/images/' . $imgName;

                            }//end if image != void
//                            else{
//                                $sendPath['img']='void';
//                            }//end else image == void
                        }//end if $categoryImg != null
                        else {
                            $sendPath['img'] = 'void';
                        }//end else $categoryImg == null


                    }//end if idImg !=0
//                    else{
//                        $sendPath['img']='void';
//                    }


                    //send total information
                    $send['img'] = $sendPath;//send img
//
                    $send['id'] = $categor->id;
                    $send['title'] = $categor->title;
                    $send['id_parent'] = $categor->id_parent;
                    $send['description'] = $categor->description;

                    $sendCategoryOk[] = $send;


                }//end foreach category

//                $sendCategoryOk[]=$send;

            }//end if $category > 0


            //send product
            $product = Product::find()->where(['enable' => 1])->andWhere(['id_participant' => $id_participant])->all();
            if ($product != null) {

                foreach ($product as $pro) {

                    //send imageProduct
                    $idPro = $pro->id;
                    $idMovie = $pro->id_img;
                    if ($idMovie != 0 && !$idMovie != -1) {
                        $productMovie = Productmove::find()->where(['enable' => 1])->andWhere(['id' => $idMovie])->andWhere(['id_product' => $idPro])->one();
                        if ($productMovie != null) {

                            $movieName = $productMovie->move1;
                            $pdfName = $productMovie->move2;
                            $imgPName = $productMovie->move3;

                            // one record
                            if ($movieName != 'void') {
                                $sendPathM['movie'] = Yii::$app->request->hostInfo . '/upload/video/' . $movieName;

                                //چون عکس هارو نمیتونستم برای هر محصول جدا بفرستم و نمیتونستم مقدار آرایه رو خالی کنم
//                                $sendPathM['movie']=null;
//                                         $all=$movieName;
//                                         $allExplode=explode('*',$all);
//
//                                         $count=count($allExplode);
//
//                                       for ($i=0 ;$i<$count ; $i++){
//
//                                           $x= $allExplode[$i];
//
////                                           $x = Yii::$app->request->hostInfo . '/upload/video/' . $allExplode[$i];
//                                           $r[]=Yii::$app->request->hostInfo .'/upload/video/'.$x;
////                                           $sendPathM['movie']=null;
//
//                                         }//end for
//
//                                       $sendPathM['movie']=$r;

                            }//end if movie != void

                            else {
                                $sendPathM['movie'] = 'void';
                            }//end else movie == void

                            // second record
                            if ($pdfName != 'void') {

                                $sendPathM['pdf'] = Yii::$app->request->hostInfo . '/upload/files/' . $pdfName;
                            }//end if movie != void
                            else {
                                $sendPathM['pdf'] = 'void';
                            }//end else movie == void

                            //third record
                            if ($imgPName != 'void') {
                                $sendPathM['img'] = Yii::$app->request->hostInfo . '/upload/images/' . $imgPName;
                            }//end if movie != void
                            else {
                                $sendPathM['img'] = 'void';
                            }//end else movie == void
//                                    var_dump($sendPathM);exit;
                            $sendPathM['imgID'] = $productMovie->id;

                        }//end if $productMovie != null
                        else {
                            $sendPathM['movie'] = 'void';
                        }//end else $productMovie == null

                    }//end if $idMovie < 1
                    else {
                        echo 0;
                        exit;
                    }//end else $idMove > 1

                    //send total information product
                    $sendProduct['title'] = $pro->title;
                    $sendProduct['typPro'] = $pro->typePro;
                    $sendProduct['id_category'] = $pro->id_Category;
//                    $sendProduct['shortDescription']=$pro->shortDescription;
//                    $sendProduct['description']=$pro->description;
                    $sendProduct['movie'] = $sendPathM;
                    $sendProduct['id'] = $pro->id;

                    $sendProductArray[] = $sendProduct;


                }//end foreach Product

                $sendProductInfo['productInfo'] = $sendProductArray;

            }//end if Product != null

//            else{
//                $sendProductInfo['productInfo']='void';
//            }//end else Product == null


            //این if رو کامنت کردم چون تعداد عکس ها و فیلم هارو مرتب تکرار میکرد
//            $category = Category::find()->where(['enable' => 1])->andWhere(['id_participant' => $id_participant])->all();
//            if ($category) {
//
//                foreach ($category as $categor) {
//
//                    $id_img=$categor->id_img;
//                    $image=Img::find()->where(['enable'=>1])->andWhere(['id'=>$id_img])->one();
//                    if ($image != null){
//                        if ($image->fileImg != 'void'){
//                            $send['img']=Yii::$app->request->hostInfo.'/upload/images/'.$image->fileImg;
//                        }
//                    }//end if image != null
//                    else{
//                        $send['img']='void';
//                    }//end else image == null
//
//                    $id_category = $categor->id;
//                    $send['id'] = $categor->id;
//                    $send['title'] = $categor->title;
//                    $send['id_parent'] = $categor->id_parent;
////                    $send['id_img'] = $categor->id_img;
//                    $send['description'] = $categor->description;
//
//                    $sendCategoryOk[] = $send;
//
//
//
//                    //second product
//                    $product = Product::find()->where(['enable' => 1])->andWhere(['id_category' => $id_category])->all();
//                    // echo 1;
//                    // var_dump($product);exit;
//                     if ($product != null) {
//
//                    foreach ($product as $pro) {
//
//                        //send product movie
//                        $id_img = $pro->id_img;
//                        if ($id_img != -1) {
//
//
//                            $movie = Productmove::find()->where(['enable' => 1])->andWhere(['id' => $id_img])->andWhere(['id_product' => $pro->id])->one();
//                            if ($movie != null) {
//
////$sendMovie['id']=$movie->id;
//                                if ($movie->move1 !='void'){
//                                    $sendMovie['movie1'] = Yii::$app->request->hostInfo . '/upload/video/' . $movie->move1;
////                                      $name=$movie->move1;
////                                         $all=Yii::$app->request->hostInfo .'/upload/video/'.$name;
////                                         $allExplode=explode('*',$all);
////
////                                         $count=count($allExplode);
////                                       for ($i=0 ;$i<$count ; $i++){
////
////                                           $x = Yii::$app->request->hostInfo . '/upload/video/' . $allExplode[$i];
////                                           $r[]=$x;
////
////                                             // var_dump($r);
////
////                                         }//end for
////
////                                       $sendMovie['movie1']=$r;
//
//
//                                }
//                                if ($movie->move2 !='void'){
//                                    $sendMovie['movie2'] = Yii::$app->request->hostInfo . "/upload/files/" . $movie->move2;
//                                }
//                                if ($movie->move3 !='void'){
//                                    $sendMovie['movie3'] = Yii::$app->request->hostInfo . "/upload/images/" . $movie->move3;
//                                }
//
//                                $sendFileMovie[] = $sendMovie;
//
//$send['movie']=$sendMovie;
////                                var_dump($send);exit;
//                            }//end if $movie
//                            else {
////                                    $sendFileMovie[] = 'void';
//                            }//end else $movie
//
//
//                        }//end if $id_img
//                        else {
////                                $sendFileMovie[] = 'void';
//                        }//end else $id_img
////                            var_dump($sendMovie);exit;
//
////                        if ($sendFileMovie != 'void'){
////                            $send['id_img'] = $sendFileMovie;
////                        }//end if $sendFileMovie
//
//
//                        $send['id'] = $pro->id;
//                        $send['title'] = $pro->title;
//                        $send['id_participant'] = $pro->id_participant;
//                        $send['typePro'] = $pro->typePro;
//                        $send['id_category'] = $pro->id_Category;
//                        $send['description'] = $pro->description;
//
//                        $sendProductOk[] = $send;
//
//                    }//end foreach
//
//
//                     }//end if product
////                     else {
//
////  $send['visits of page'] = $sumVisits;
////                         $send['category'] = $sendCategoryOk;
////                         $send['result'] = 0;
////                         $send['msg'] = 'در این غرفه هیچ محصولی وجود ندارد';
////                         return $send;
////                     }
//                }//end foreach $category
//
//            }//ens if $category

            $sendOk['visits of page'] = $sumVisits;
            $sendOk['category'] = $sendCategoryOk;
            $sendOk['product'] = $sendProductInfo;

            $sendOk['result'] = 1;
            return $sendOk;

        }//end isset
        else {

            $send['result'] = 0;
            $send['msg'] = 'در حال حاضر چنین غرفه ای وجود ندارد';
            return $send;
        }//end else isset
    }

//send number of visits in app
    public
    function actionViews()
    {
//        $view=Views::find()->all();
        $date = date('Y/m/d');
        $view = Views::find()->where(['date' => $date])->all();
        $sumVisits = 0;
        foreach ($view as $visit) {
            $numberVisit = $visit->visits;
            $sumVisits = $sumVisits + $numberVisit;
        }
        echo $numberVisit;
        exit;

    }

//send view visitirs
    public
    function actionViewfiles()
    {
        if (isset($_POST['fileName']) && $_POST['fileName'] != null
            && isset($_POST['id_participant']) && $_POST['id_participant'] != null
        ) {
            $idParticipant = $_POST['id_participant'];
            $fileName = $_POST['fileName'];

            //بدست آوردن تاریخ پایان نمایشگاه
            $participant = Participant::find()->where(['id' => $idParticipant])->andWhere(['enable' => 1])->one();
            $idExhibition = $participant->id_exhibitionn;
            $exhibition = Exhibitionn::find()->where(['enable' => 1])->andWhere(['id' => $idExhibition])->one();
            $exhibitionHistoryC = $exhibition->completion_date_ir;
            $exhibitionHistoryH = $exhibition->holding_date_ir;//تاریخ شروع نمایشگاه

            //تبدیل تاریخ برای مقایسه
            $exhibitionHistory1 = strtotime($exhibitionHistoryC);


            //جدا کردن نام و پسوند
            $fileExtension = explode(".", $fileName);
            $name = $fileExtension[0];//file name
            $extension = $fileExtension[1];

            //search in folder
            if ($extension == 'pdf') {

                if (yii::getAlias('@upload') . 'upload/files' . $fileName) {

                    $view = Views::find()->where(['date' => $exhibitionHistoryC])->andWhere(['id_participant' => $idParticipant])->andWhere(['enable' => 1])->all();
                    $sumVisits = 0;
                    foreach ($view as $visit) {
                        $numberVisit = $visit->file_visits;
                        $sumVisits = $sumVisits + $numberVisit;
                        $visits1 = $visit->visits;
                    }

//save number of visits in app
                    $visitsPage = new Views();
                    $visitSum = 0;
                    $count = Views::find()->where(['id_participant' => $idParticipant])->andWhere(['date' => $exhibitionHistoryC])->andWhere(['enable' => 1])->andWhere(['file_name' => $name])->count();

                    if ($count == 0) {

                        $write = Views::find()->where(['id_participant' => $idParticipant])->andWhere(['date' => $exhibitionHistoryC])->andWhere(['enable' => 1])->one();
                        if ($write->file_name == null || $write->file_name == 0) {

                            $visitSum = $visitSum + 1;
                            $write->file_visits = $visitSum;
                            $write->id_participant = $idParticipant;
                            $write->date = $exhibitionHistoryC;
                            $write->file_name = $name;
                            if ($write->save()) {

                            }//end if save
                            else {

                                var_dump($write->getErrors());
                                exit;
                            }//end else save
                        }//end if file name = null
                        elseif ($write->file_name != $name) {

                            $visitSum = $visitSum + 1;
                            $visitsPage->file_visits = $visitSum;
                            $visitsPage->id_participant = $idParticipant;
                            $visitsPage->date = $exhibitionHistoryC;
                            $visitsPage->file_name = $name;
                            $visitsPage->visits = $write->visits;
                            if ($visitsPage->save()) {

                            }//end if save
                            else {
                                var_dump($visitsPage->getErrors());
                                exit;
                            }//end else save
                        }


                    }//end if count
                    else {
                        $doubleWrite = Views::find()->where(['id_participant' => $idParticipant])->andWhere(['date' => $exhibitionHistoryC])->andWhere(['enable' => 1])->andWhere(['file_name' => $name])->one();
                        $id = $doubleWrite->id;
                        $write = Views::find()->where(['id' => $id])->one();
                        $visitSum = $write->file_visits + 1;
                        $write->file_visits = $visitSum;
                        if ($write->save()) {

                        }//end if write
                        else {
                            var_dump($write->getErrors());
                            exit;
                        }


                    }//end else count


                }//end if the file was in the folder
                else {
                    echo 9;
                    exit;
                }//end else the file dose not exist in the folder
            }//end if pdf
            else {
            }//end else movie


        }//ene if isset
        else {
            $send['result'] = 0;
//            $send['msg'] = 'در حال حاضر چنین غرفه ای وجود ندارد';
//            return $send;
        }//end else isset

//        if (isset($_POST['id_participant']) && $_POST['id_participant'] != null) {
//            $date = date('Y-m-d');
//            $id = $_POST['id_participant'];
//            $view = Views::find()->where(['id_participant' => $id])->all();
//            if ($view) {
//
//                foreach ($view as $v) {
//                    $viewDate = $v->date;
////                    var_dump($date);
////                    var_dump($viewDate);exit;
//                    if ($viewDate == $date) {
//                        $views = $v->visits;
//                        $ok = 1;
//                    }//end if $viewDate==$date
//                    else {
//                        $ok = 0;
//                    }//end else $viewDate==$date
//
//                }//end foreach
//
//                if ($ok == 1) {
//                    $sendOk['result'] = 1;
//                    $sendOk['visits'] = $views;
//                    $sendOk['msg'] = 'تعداد بازدید های امروز این غرفه';
//                    return $sendOk;
//                }//end if ok
//                else {
//
//                    $send['result'] = 0;
//                    $send['msg'] = 'غرفهای وجود ندارد';
//                    return $send;
//                }//end else ok
//
//            }//end if $views
//            else {
//
//                $send['result'] = 0;
//                $send['msg'] = 'غرفهای وجود ندارد';
//                return $send;
//            }//end else $views
//        }//end if isset
//        else {
//            $send['result'] = 0;
//            $send['msg'] = 'لطفا در ایتدا نام غرفه را انتخاب کنید.';
//            return $send;
//        }

    }

}

