<?php
/**
 * Created by PhpStorm.
 * User: maryam
 * Date: 7/29/2018
 * Time: 1:34 PM
 */

namespace common\components;

use yii;
use common\models\User;
use yii\base\Component;
use frontend\models\Profile;

class Proofile extends Component
{

    private $session;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->session = Yii::$app->session;
    }

//چک کردن نام کاربریemail
    public function chekUsername($username)
    {
        $chek = User::find()->where(['username' => $username])->one();

        if ($chek != null) {
            $sendOk['result'] = 0;
            $sendOk['msg'] = "ایمیل شما تکراری می باشد";

            return $sendOk;
        }
    }

    public function Signup(

        $username,
        $password,
        $company_name_en,
        $company_name_ir,
//          $email,
        $telephone,
        $mobile,
        $rules,
        $role,
//        $id_user,
        $id_img,
        $date,
        $date_ir,
        $date_update,
        $date_update_ir,
        $name,
        $state,
        $code,
        $enable
    )
    {
        $user = new User();
        $user->username = $username;
        $user->setPassword($password);
        $user->generateAuthKey();

        $auth = Yii::$app->authManager;
        $authoRole = $auth->getRole($role);
        if ($user->save()) {
            $auth->assign($authoRole, $user->id);

            $Profile = new Profile();
            $Profile->company_name_en = $company_name_en;
            $Profile->company_name_ir = $company_name_ir;
//            $Profile->email = $email;
            $Profile->telephone = $telephone;
            $Profile->mobile = $mobile;
            $Profile->rules = $rules;
//            $Profile->id_user = $id_user;
            $Profile->id_img = $id_img;
            $Profile->date = $date;
            $Profile->date_ir = $date_ir;
            $Profile->date_update = $date_update;
            $Profile->date_update_ir = $date_update_ir;
            $Profile->name = $name;
            $Profile->state = $state;
            $Profile->code = $code;
            $Profile->enable = $enable;

            if ($Profile->save()) {
                $send['result'] = 1;
                $send['msg'] = "ثبت نام با موفقیت انجام شد لطفا برای فعال کردن حساب کاربری در ایمیل خود تاییدیه ایمیل خود را ارسال کنید";
                return null;
            } else {
                $send['result'] = -1;
                $send['msg'] = "ثبت نام ناموفق";
                return null;
            }


        } else {
            $send['result'] = 0;
            $send['msg'] = "ثبت نشد";
            return null;

        }

    }


//قسمت login
    public function Login($username, $password)
    {
        $user = User::findByUsername($username);
        if ($user != null) {
            if ($user->validatePassword($password)) {
                if (Yii::$app->getUser()->login($user)) {
                    $profile = Profile::find()->where(['enable' => 1])->andWhere(['id_user' => $user->id])->one();
                    if ($profile != null) {
                        if ($profile->state = 1) {
                            if ($profile->enable = 1) {
                                $send['id'] = $profile->id;
                                $send['company_name_en'] = $profile->company_name_en;
                                $send['company_name_ir'] = $profile->company_name_ir;
                                $send['name'] = $profile->name;
                            } else {
                                $send['result'] = -4;
                                $send['msg'] = "خطا دسترسی شما محدود شده.";
                                return $send;
                            }
                        } else {
                            $send['result'] = -3;
                            $send['msg'] = "حساب کاربری هنوز فعال نشده است.";
                            return $send;
                        }
                    } else {
                        $send['result'] = -4;
                        $send['msg'] = "خطا دسترسی شما محدود شده.";
                        return $send;
                    }
                    return $send;
                } else {
                    $send['return'] = -2;
                    $send['msg'] = 'خطا . دوباره امتحان کنید.';
                    return $send;
                }
            } else {
                $send['result'] = -1;
                $send['msg'] = "پسورد اشتباه است";
                return $send;
            }
        } else {
            $send['result'] = 0;
            $send['msg'] = "نام کابری اششتباه است.";
            return $send;
        }


    }

//قسمت view
    public function ViewProfile($role, $iduser)
    {
        $profile = Profile::find()->where(['id_user' => $iduser])->andWhere(['role' => $role])->andWhere(['enable' => 1])->all();
        if ($profile != null) {
            if ($role == 'booth') {
                $send['company_name_en'] = $profile->company_name_en;
                $send['company_name_ir'] = $profile->company_name_ir;
                $send['mobile'] = $profile->mobile;
                $send['telephone'] = $profile->telephone;

                $send['result'] = 1;
                $sendlist = $send;
                return $sendlist;
            } elseif ($role == 'user') {
                $send['name'] = $profile->name;
                $send['mobile'] = $profile->mobile;
                $send['telephone'] = $profile->telephone;

                $send['result'] = 1;
                $sendlist = $send;
                return $sendlist;
            } else {
                $send['result'] = -1;
                $send['msg'] = "لطفا نقش خود را واردکنید";
                return $send;
            }
        } else {
            $send['result'] = 0;
            $send['msg'] = "نقش را درست واروکنید";
            return $send;
        }
    }

    //قسمت update
    public function UpdateProfile(
        $iduser,
        $role,
        $company_name_en,
        $company_name_ir,
        $telephone,
        $mobile,
        $id_img,
        $name
    )
    {
        $profile = Profile::find()->where(['id_user' => $iduser])->andWhere(['role' => $role])->andWhere(['enable' => 1])->all();
        if ($profile != null) {
            foreach ($profile as $pro) {
                if ($role == 'booth') {
                    $pro->company_name_en = $company_name_en;
                    $pro->company_name_ir = $company_name_ir;
                    $pro->telephone = $telephone;
                    $pro->mobile = $mobile;
                    $pro->id_img = $id_img;

                    if ($pro->save()) {
                        $send['result'] = 1;
                        $send['msg'] = "عملیات با موفقیت انجام شد";
                    } else {
                        $send['result'] = -1;
                        $send['msg'] = "عملیات ناموفق";
                    }
                } elseif ($role == 'user') {
                    $pro->name = $name;
                    $pro->telephone = $telephone;
                    $pro->mobile = $mobile;
                    $pro->id_img = $id_img;
                } else {

                }
            }
            return $send;
        } else {
            $send['result'] = 0;
            $send['msg'] = "این کاربر وجود ندارد";
            return $send;
        }
    }
}
